### ISSUE TITLE
QuerySelector Vars

### ISSUE THREAD

**Issue by Phizzard** [rotunstall/To-Do-List#1]
https://github.com/rotunstall/To-Do-List/blob/6bd7c8e3fc7808db37baf64e87c46825a16bc0e1/app.js#L1-L8

I like that you organized selected elements you would need handy into variables, however, there is 2 problems with this specific implementation.

**1.**
https://github.com/rotunstall/To-Do-List/blob/6bd7c8e3fc7808db37baf64e87c46825a16bc0e1/app.js#L7-L8

The difference between these 3 selectors and the ones before it, is that these elements don't exist in the DOM, until they are created later on in the Javascript. 

So when `const editItem = document.querySelector('.edit-item'); ` happens, it's not storing the execution of this, it's storing the return value of the `querySelector` function which in this point in the code is `null`.

These `document.querySelector`s would have to run while the elements it's selecting exists in the DOM.
**2.**

Both `editItem` and `completed` are defined, but never used in the code and should be removed.

**Comment by rotunstall** [comment]
I think I got a little carried away with trying to be organized. I had plans to go back and clean up unused or unnecessary code bits. I guess a part of becoming more experience you kind of know what you need and how to implement it as you go. I will try to keep this in mind. Thanks.
