### ISSUE TITLE
Comments are great, but use them when context may not be clear

### ISSUE THREAD

**Issue by Phizzard** [rotunstall/To-Do-List#2]
Comments can be very useful in describing pieces of application logic that may be complex or unclear from reading the code.

This also means that it's best to avoid commenting code that can be self-described.

A few examples:
**1.**
https://github.com/rotunstall/To-Do-List/blob/9f4293b01a4e9c3dca1f56d47ce5441dbcc8ca58/app.js#L13-L14

**2.**
https://github.com/rotunstall/To-Do-List/blob/9f4293b01a4e9c3dca1f56d47ce5441dbcc8ca58/app.js#L15-L24

**3.**
https://github.com/rotunstall/To-Do-List/blob/9f4293b01a4e9c3dca1f56d47ce5441dbcc8ca58/app.js#L39-L40

**4.**
https://github.com/rotunstall/To-Do-List/blob/9f4293b01a4e9c3dca1f56d47ce5441dbcc8ca58/app.js#L69-L70

**5.**
https://github.com/rotunstall/To-Do-List/blob/9f4293b01a4e9c3dca1f56d47ce5441dbcc8ca58/app.js#L129-L130

For situations like this, I would recommend removing comments like these as it will improve the readability of the code. It's also easier to trust code than comments when it comes to the longevity of a codebase.

**Comment by rotunstall** [comment]
You are very right about this. I had to move some code around and I did not take the comments that corresponded with it. When I went back later to clean things up, it was a little confusing until I realized what I had done. Now imagine, if this was months later or if it was not my code, to begin with.
