### ISSUE TITLE
Set events on created elements rather than container

### ISSUE THREAD

**Issue by Phizzard** [rotunstall/To-Do-List#3]
https://github.com/rotunstall/To-Do-List/blob/6bd7c8e3fc7808db37baf64e87c46825a16bc0e1/app.js#L20
https://github.com/rotunstall/To-Do-List/blob/6bd7c8e3fc7808db37baf64e87c46825a16bc0e1/app.js#L77-L130

The issues with this:

1. is that every click, even on non-interactable sections, will execute javascript.

2. The conditional logic for each action will grow to be unmaintainable and prone to bugs.

I would recommend setting the event logic as you create the element.

**For Example**
```js
  const editLink = document.createElement("a");
  editLink.className = "edit-item";
  editLink.innerHTML = '<i class="small material-icons">edit</i>';
  editLink.onclick = someEditFunction(); <<<<<<
  newLi.appendChild(editLink);
```

**Comment by Phizzard** [comment]
My example was wrong! Apologies.

This is what it would look like!
```js
const editLink = document.createElement("a");
  editLink.className = "edit-item";
  editLink.innerHTML = '<i class="small material-icons">edit</i>';
  editLink.onclick = someEditFunction; <<<<<<
  newLi.appendChild(editLink);
```

**Comment by rotunstall** [comment]
Thanks for the tip. I was able to implement this and it is much more concise, manageable, and understandable (once I got the syntax right). This will be a big help going forward.
