### ISSUE TITLE
Clousures are on the more complex side and very powerful

### ISSUE THREAD

**Issue by Phizzard** [rotunstall/To-Do-List#7]
https://github.com/rotunstall/To-Do-List/blob/6bd7c8e3fc7808db37baf64e87c46825a16bc0e1/app.js#L40-L53

Good job in utilizing closures!

**Comment by rotunstall** [comment]
Thanks, I actually replaced this in the code. I wasn't completely comfortable with the implementation but I knew it could serve a purpose at the time. I would like to learn more about it and see how and when it should be properly used.
