### ISSUE TITLE
Store todo items as an object

### ISSUE THREAD

**Issue by Phizzard** [rotunstall/To-Do-List#8]
Currently, Todos are stored as a list of arrays in local storage.

`['first todo', 'second todo']`

I would recommend using an array of objects to store more data about each todo to help simplify the logic. This will help the needed functionality be data-driven.

```js
[
  {
    id: 0,
    value: "first todo",
    checked: false
  },
  {
    id: 1,
    value: "second todo",
    checked: true
  }
]
```

The **id** would be a unique identifier for each todo to help target the item needed to edit, check, or remove.

The **value** would be the text for the task.

The **checked** would keep track of an item's checked attribute

**Comment by rotunstall** [comment]
implemented this in current update of WIP-To-Do-List
I still think after adding this the code can use the new data structure to be more efficient (using splice instead of always redrawing the task list from local storage) just have not figured out how to implement it

**Comment by rotunstall** [comment]
refactored with array of objects within the app (not just for local storage) this has been pushed to WIP branch on 04/25/2020
